export const destinationData = [
  {
    title: 'Kodak Portra 160',
    image: require('../../assets/hotel.png'),
    specs: {
      'film simulation': 'Classic Chrome',
      'dynamic range': 'DR400',
      'grain effect': 'Weak, Small',
      'color chrome effect': 'Strong',
      'color chrome fx blue': 'Strong',
      'white balance': '4900K, +4 Red & -6 Blue',
      highlight: '-1',
      shadow: '-2',
      color: '0',
      sharpness: '-2',
      nr: '-4',
      clarity: '-3',
      iso: 'Auto',
      'exposure compensation': '+1'
    }
  },
//   {
//     title: 'Kodak Portra 160',
//     'film simulation': 'Classic Chrome',
//     'dynamic range': 'DR400',
//     'grain effect': 'Weak, Small',
//     'color chrome effect': 'Strong',
//     'color chrome fx blue': 'Strong',
//     'white balance': '4900K, +4 Red & -6 Blue',
//     highlight: '-1',
//     shadow: '-2',
//     color: '0',
//     sharpness: '-2',
//     nr: '-4',
//     clarity: '-3',
//     iso: 'Auto',
//     'exposure compensation': '+1',
//     image: require('../../assets/hotel.png')
//   },
//   {
//     title: 'Kodak Portra 160',
//     'film simulation': 'Classic Chrome',
//     'dynamic range': 'DR400',
//     'grain effect': 'Weak, Small',
//     'color chrome effect': 'Strong',
//     'color chrome fx blue': 'Strong',
//     'white balance': '4900K, +4 Red & -6 Blue',
//     highlight: '-1',
//     shadow: '-2',
//     color: '0',
//     sharpness: '-2',
//     nr: '-4',
//     clarity: '-3',
//     iso: 'Auto',
//     'exposure compensation': '+1',
//     image: require('../../assets/hotel.png')
//   },
//   {
//     title: 'Kodak Portra 160',
//     'film simulation': 'Classic Chrome',
//     'dynamic range': 'DR400',
//     'grain effect': 'Weak, Small',
//     'color chrome effect': 'Strong',
//     'color chrome fx blue': 'Strong',
//     'white balance': '4900K, +4 Red & -6 Blue',
//     highlight: '-1',
//     shadow: '-2',
//     color: '0',
//     sharpness: '-2',
//     nr: '-4',
//     clarity: '-3',
//     iso: 'Auto',
//     'exposure compensation': '+1',
//     image: require('../../assets/hotel.png')
//   },
//   {
//     title: 'Kodak Portra 160',
//     'film simulation': 'Classic Chrome',
//     'dynamic range': 'DR400',
//     'grain effect': 'Weak, Small',
//     'color chrome effect': 'Strong',
//     'color chrome fx blue': 'Strong',
//     'white balance': '4900K, +4 Red & -6 Blue',
//     highlight: '-1',
//     shadow: '-2',
//     color: '0',
//     sharpness: '-2',
//     nr: '-4',
//     clarity: '-3',
//     iso: 'Auto',
//     'exposure compensation': '+1',
//     image: require('../../assets/hotel.png')
//   },
//   {
//     title: 'Kodak Portra 160',
//     'film simulation': 'Classic Chrome',
//     'dynamic range': 'DR400',
//     'grain effect': 'Weak, Small',
//     'color chrome effect': 'Strong',
//     'color chrome fx blue': 'Strong',
//     'white balance': '4900K, +4 Red & -6 Blue',
//     highlight: '-1',
//     shadow: '-2',
//     color: '0',
//     sharpness: '-2',
//     nr: '-4',
//     clarity: '-3',
//     iso: 'Auto',
//     'exposure compensation': '+1',
//     image: require('../../assets/hotel.png')
//   }
]
